# This file was generated by GoReleaser. DO NOT EDIT.
cask "cider" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "45313e297b922fdb5d816dad01825e8dc84e8b2d244e49e59da37c5ebfc3781c"
      url "https://github.com/Gaurav-Gosain/cider/releases/download/v#{version}/cider_#{version}_Darwin_arm64.tar.gz"
    end
  end

  name "cider"
  desc "Apple Foundation Models, in Go. On-device, private, no cgo."
  homepage "https://github.com/Gaurav-Gosain/cider"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cider"

  postflight do
    system_command "/usr/bin/xattr",
      args: ["-dr", "com.apple.quarantine", staged_path],
      sudo: false
  end

  # No zap stanza required

  caveats <<~EOS
    cider needs Apple Intelligence enabled in System Settings → Apple
    Intelligence & Siri.

    The binary is not notarised. If macOS blocks the first run, open
    System Settings → Privacy & Security and click "Allow Anyway",
    or run:
      xattr -dr com.apple.quarantine "$(brew --caskroom)/cider"
  EOS
end
