# This file was generated by GoReleaser. DO NOT EDIT.
cask "scraped" do
  name "scraped"
  desc "A fast, parallelized CLI tool that scrapes web pages and converts them to markdown"
  homepage "https://github.com/Gaurav-Gosain/scraped"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scraped"

  on_macos do
    on_intel do
      url "https://github.com/Gaurav-Gosain/scraped/releases/download/v#{version}/scraped_#{version}_Darwin_x86_64.tar.gz"
      sha256 "83d9b203ce24c3d74b712a7ddbda62f92881a22360a824e29adb587063e4c267"
    end
    on_arm do
      url "https://github.com/Gaurav-Gosain/scraped/releases/download/v#{version}/scraped_#{version}_Darwin_arm64.tar.gz"
      sha256 "3b76e53764fd2bb32dd25fe9e5180f7bebfdbf1650658b120a6c1c54d6e35571"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Gaurav-Gosain/scraped/releases/download/v#{version}/scraped_#{version}_Linux_x86_64.tar.gz"
      sha256 "d88c95afefa95af603c5e84b65c403419cd69e868a800b098d90a37140daa933"
    end
    on_arm do
      url "https://github.com/Gaurav-Gosain/scraped/releases/download/v#{version}/scraped_#{version}_Linux_arm64.tar.gz"
      sha256 "35fb1072f7a84f9f6feef1e9ac3f48eb3bf83cabe2ce91000e9e3b574cf1bcc2"
    end
  end

  # No zap stanza required
end
