# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuios-web" do
  name "tuios-web"
  desc "Web terminal server for TUIOS - Serves TUIOS through the browser"
  homepage "https://github.com/Gaurav-Gosain/tuios"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuios-web"

  on_macos do
    on_intel do
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios-web_#{version}_Darwin_x86_64.tar.gz"
      sha256 "36553fbe8300a5d75adac7c7a5ac832e2a111a1aeb03d8cd43199bfa1801ce00"
    end
    on_arm do
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios-web_#{version}_Darwin_arm64.tar.gz"
      sha256 "163c32a02e86dcc760566e5c5360eb0e101050890bf0f01938e1e200ff160363"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios-web_#{version}_Linux_x86_64.tar.gz"
      sha256 "72d4a106b2eecab9ccd76c39ed501d1a50404d57161668591b1296685030e577"
    end
    on_arm do
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios-web_#{version}_Linux_arm64.tar.gz"
      sha256 "65c6737066b94cf4082d8875757383ad7609b11bd5ca5f3c5faa82d4afbf8b7f"
    end
  end

  # No zap stanza required
end
