# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuios" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "671433256bb256491a8d72555fcdf256797d68abb9de2b0e073b16cd95559821"
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1000866a358a43e6b49df4eadde811617535b854f60d880d4862ce7415209e24"
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "31fce4339d96c743204e1031f9728677e9ed99c5e1aad835c2ced42a532b87c4"
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8246b6dae6fdb89a00d7e171fec1143d72d877ebfe93c4d866199ea8702c6a96"
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "tuios"
  desc "Terminal UI Operating System - A terminal-based window manager with tmux-style keybindings"
  homepage "https://github.com/Gaurav-Gosain/tuios"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuios"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tuios"]
    end
  end

  # No zap stanza required
end
