# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuios" do
  name "tuios"
  desc "Terminal UI Operating System - A terminal-based window manager with tmux-style keybindings"
  homepage "https://github.com/Gaurav-Gosain/tuios"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuios"

  on_macos do
    on_intel do
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios_#{version}_Darwin_x86_64.tar.gz"
      sha256 "d61ddb2d5bdf92f10e17786b9dedfc3dcd717fff79568c49f676012c8fff0abe"
    end
    on_arm do
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios_#{version}_Darwin_arm64.tar.gz"
      sha256 "bfc1d606ac71fdf9e0c729d7f6e9646045e1f43e6007e5f275b94924114dac66"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios_#{version}_Linux_x86_64.tar.gz"
      sha256 "58da111fd0132e8fb1e96a9a89a7166dfafa727d5af60bb2b60e394025bf4dbd"
    end
    on_arm do
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios_#{version}_Linux_arm64.tar.gz"
      sha256 "158a0f0a51f6d757a8aa9fcc2b4babb56d7f3e9e1b23786a8d123abb7868adff"
    end
  end

  # No zap stanza required
end
