# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuios-ghostty" do
  version "0.9.0"

  on_linux do
    on_arm do
      sha256 "c87434316084ac9962d296b82365664cd24d26f832a14f648f04d4b901c10cd6"
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios-ghostty_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "aa0109fa03d160971c764c0e0b7828c76d8c0064466b90f4674895d252170e34"
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios-ghostty_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "tuios-ghostty"
  desc "TUIOS built with the libghostty-vt terminal engine. Linux only."
  homepage "https://github.com/Gaurav-Gosain/tuios"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "tuios",
    ]

  binary "tuios"

  # No zap stanza required

  caveats <<~EOS
    tuios-ghostty installs a binary named tuios.
    The tuios formula installs a binary with the same name.
    Uninstall the formula before you install this cask:
      brew uninstall tuios
    To go back to the formula, run:
      brew uninstall --cask tuios-ghostty
      brew install tuios
  EOS
end
