# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuios-ghostty" do
  version "0.9.1"

  on_linux do
    on_arm do
      sha256 "3658806e11d194c62c5d1b8ced39d1ea378685a79cc97eea33c9390ed40c4eb9"
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios-ghostty_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6370ff5a0de170755d42db7d3dfa0dab10c15609f81e321c114865f785798c29"
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios-ghostty_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "tuios-ghostty"
  desc "TUIOS built with the libghostty-vt terminal engine. Linux only."
  homepage "https://github.com/Gaurav-Gosain/tuios"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "tuios",
    ]

  binary "tuios"

  # No zap stanza required

  caveats <<~EOS
    tuios-ghostty installs a binary named tuios.
    The tuios formula installs a binary with the same name.
    Uninstall the formula before you install this cask:
      brew uninstall tuios
    To go back to the formula, run:
      brew uninstall --cask tuios-ghostty
      brew install tuios
  EOS
end
