# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuios" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/tuios"]
    end
  end

  version "0.8.5"

  on_macos do
    on_arm do
      sha256 "0a2a5b66829282d133b4d222c93045f7d392ee942687c7dd34f6cbd3bc7d4d61"
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4cc2609e1183e483807b50cc3f2a4bd11da1a10d8094c085a3575732c7a078c2"
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8be4855546fb3567de25a65d7268d6ed8de28ccefbd07b5b34785e2bea8b2851"
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "48c8604f266ad8680b925f8ba6618d9506de46c2bce5d5e507b86a5c91646f1e"
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "tuios"
  desc "Terminal UI Operating System - A terminal-based window manager with tmux-style keybindings"
  homepage "https://github.com/Gaurav-Gosain/tuios"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuios"

  # No zap stanza required
end
