# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuios-ghostty" do
  version "0.9.2"

  on_linux do
    on_arm do
      sha256 "ab71670a987810e40ab9fc70e17d9a3ae0092032569c8e8773eaf7cff41448a6"
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios-ghostty_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "739eac52713cf6037891d58925c03778aa8b7456bdf370204889ba2a499d7665"
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios-ghostty_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "tuios-ghostty"
  desc "TUIOS built with the libghostty-vt terminal engine. Linux only."
  homepage "https://github.com/Gaurav-Gosain/tuios"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "tuios",
    ]

  binary "tuios"

  # No zap stanza required

  caveats <<~EOS
    tuios-ghostty installs a binary named tuios.
    The tuios formula installs a binary with the same name.
    Uninstall the formula before you install this cask:
      brew uninstall tuios
    To go back to the formula, run:
      brew uninstall --cask tuios-ghostty
      brew install tuios
  EOS
end
