# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuios-web" do
  version "0.8.1"

  on_macos do
    on_arm do
      sha256 "b58aa1229ca561aecb6257a55837ded15aebbd64bd78f88eca0beb06ae5467b2"
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios-web_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ee18cf55fae7e81aca10ff706bf1a781167883e49af8277d01204a4f129aa4db"
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios-web_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "75a0bce5c4ef7c8e37fa01f674021f3f754e7db263fbd887bd365285e31e5fc6"
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios-web_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "29785df1fc165a8a4978b1313a2c8dd2123285cc2f8176c72cff837a5f9d3f17"
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v#{version}/tuios-web_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "tuios-web"
  desc "Web terminal server for TUIOS - Serves TUIOS through the browser"
  homepage "https://github.com/Gaurav-Gosain/tuios"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuios-web"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tuios-web"]
    end
  end

  # No zap stanza required
end
