# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Golars < Formula
  desc "Pure-Go DataFrames modeled on polars. Eager + lazy + streaming, no cgo."
  homepage "https://golars.gaurav.zip"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gaurav-Gosain/golars/releases/download/v0.1.1/golars_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "e8f7f24362577caa061277deedad56b5300e303389eb24c669db14bfc26785f6"

      define_method(:install) do
        bin.install "golars"
        bin.install "golars-lsp"
        bin.install "golars-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gaurav-Gosain/golars/releases/download/v0.1.1/golars_0.1.1_Darwin_arm64.tar.gz"
      sha256 "a6094bd123671742ef5bbf17811268fd20c7d6a81a0181053e1eee748c71ca7b"

      define_method(:install) do
        bin.install "golars"
        bin.install "golars-lsp"
        bin.install "golars-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gaurav-Gosain/golars/releases/download/v0.1.1/golars_0.1.1_Linux_x86_64.tar.gz"
      sha256 "fcaa944a12bd59403deccf278661fadc26dd0cc250c955e29cbc0936babdc100"
      define_method(:install) do
        bin.install "golars"
        bin.install "golars-lsp"
        bin.install "golars-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gaurav-Gosain/golars/releases/download/v0.1.1/golars_0.1.1_Linux_arm64.tar.gz"
      sha256 "84456abfc03913255347abe48dca677e1b3cc4b22a22588a7fa299bf596d45f3"
      define_method(:install) do
        bin.install "golars"
        bin.install "golars-lsp"
        bin.install "golars-mcp"
      end
    end
  end

  test do
    system "#{bin}/golars", "version"
  end
end
