# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Golars < Formula
  desc "Pure-Go DataFrames modeled on polars. Eager + lazy + streaming, no cgo."
  homepage "https://golars.gaurav.zip"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gaurav-Gosain/golars/releases/download/v0.1.8/golars_0.1.8_Darwin_x86_64.tar.gz"
      sha256 "8b8ac1a3709c855be61151dde27a4ab53dc199770cab96d98e4798f3be6748bb"

      define_method(:install) do
        bin.install "golars"
        bin.install "golars-lsp"
        bin.install "golars-mcp"
        bin.install "golars-kernel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gaurav-Gosain/golars/releases/download/v0.1.8/golars_0.1.8_Darwin_arm64.tar.gz"
      sha256 "1651006c532678ebbaf4ca528f0b07ccf6d78e1f02c3082445293bbb6bb8a643"

      define_method(:install) do
        bin.install "golars"
        bin.install "golars-lsp"
        bin.install "golars-mcp"
        bin.install "golars-kernel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gaurav-Gosain/golars/releases/download/v0.1.8/golars_0.1.8_Linux_x86_64.tar.gz"
      sha256 "794b8eac5d559e89581218a1b01bdd9fd903d2d5c1d095d943223f9117f9abfd"
      define_method(:install) do
        bin.install "golars"
        bin.install "golars-lsp"
        bin.install "golars-mcp"
        bin.install "golars-kernel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gaurav-Gosain/golars/releases/download/v0.1.8/golars_0.1.8_Linux_arm64.tar.gz"
      sha256 "6391438950c65f90977c935574792e45b561b60df26581b822f99d58049b889d"
      define_method(:install) do
        bin.install "golars"
        bin.install "golars-lsp"
        bin.install "golars-mcp"
        bin.install "golars-kernel"
      end
    end
  end

  test do
    system "#{bin}/golars", "version"
  end
end
