# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tuios < Formula
  desc "Terminal UI Operating System - A terminal-based window manager with tmux-style keybindings"
  homepage "https://github.com/Gaurav-Gosain/tuios"
  version "0.0.24"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v0.0.24/tuios_0.0.24_Darwin_x86_64.tar.gz"
      sha256 "b7f508115fdef34410e4efe62f72e883d8e42878da7c53636ee1d45219d81107"

      def install
        bin.install "tuios"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v0.0.24/tuios_0.0.24_Darwin_arm64.tar.gz"
      sha256 "90edc149684100d1712cf889f0d7b959ce2c62b60628943faae3765b50cb4b8b"

      def install
        bin.install "tuios"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v0.0.24/tuios_0.0.24_Linux_x86_64.tar.gz"
      sha256 "5de5d7b9e351042d8209ac251678a86ec3cf91bfe972ce8c114146e33507d8d4"
      def install
        bin.install "tuios"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v0.0.24/tuios_0.0.24_Linux_armv6.tar.gz"
      sha256 "aeca507987f49cc14f5f53606308ca7f5f71635de63c52d10a4729d96a16b5fc"
      def install
        bin.install "tuios"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gaurav-Gosain/tuios/releases/download/v0.0.24/tuios_0.0.24_Linux_arm64.tar.gz"
      sha256 "09e9a29adf668ca85718d5e352734fc9bf624501c88710533687f94e90560180"
      def install
        bin.install "tuios"
      end
    end
  end

  test do
    system "#{bin}/tuios", "--version"
  end
end
